Importer stillinger
navikt/rekrutteringsbistand-container pull request #13
Opened 2020-11-13 07:35 UTC by joarau

2020-11-13 12:28 UTC, andrmos approved these changes

2020-11-16 14:56 UTC, kjesvale commented on public/index.html
> -        <script type="text/javascript" src="/kandidater/js/env.js"></script>
Sykt. Digg.

2020-11-16 14:58 UTC, kjesvale commented on src/microfrontend/useAppAssets.ts
> +                let liste: string[] = staticPaths;
Rename denne til noe bedre? Hva med å kalle denne for `pathsToLoad` og rename den på L58 til `pathsFromManifest`?

2020-11-16 15:09 UTC, kjesvale requested changes
Bra hvis du fikser det variabelnavnet!

2020-11-17 07:24 UTC, merged